[package]
name = "aoc_24_day1"
version = "0.1.0"
authors = ["Mark Ingram <mark@lincs.dev>"]
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.93"
wasi = "0.13.3"
